# Generated by Django 5.1.1 on 2024-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementprepdjango', '0002_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
