# Generated by Django 5.1.1 on 2024-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementprepdjango', '0003_alter_quiz_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
