# Generated by Django 5.1.1 on 2024-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementprepdjango', '0004_alter_quiz_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('test_cases', models.JSONField()),
                ('language', models.CharField(blank=True, choices=[('C', 'C'), ('Java', 'Java'), ('Python', 'Python'), ('C++', 'C++')], max_length=20, null=True)),
            ],
        ),
    ]
