# Generated by Django 5.1.1 on 2024-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementprepdjango', '0005_codingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
