# Generated by Django 5.1.1 on 2024-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementprepdjango', '0006_topic_image_topic_prompt_alter_topic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('advanced', 'Advanced')], max_length=10)),
            ],
        ),
    ]
