# Generated by Django 5.1.1 on 2025-04-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementprepdjango', '0009_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
